# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddff9f588842d0a120b6d2d3470a0271b7752cd97717d3d50f174bccdb7ebe0fdaef17a136fa51018aea2fc96fdf29247fa04dcb9647649fb54ed0e2fc5395af

test:
  secret_key_base: 50ee7d4ecb6f76c1a14c1dbec219fbf1a77d4913f9b8fed973ce1e9067c55a2474bbaa353adce407de16b7e2c93107dba926e55de02aaab6074d10d368974444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
